version: '3.8'

services:
  cypress-runner-1:
    image: my-cypress-project
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
      - ./cypress/reports:/app/cypress/reports
    environment:
      - AWS_ACCESS_KEY_ID=AKIAYPLNK36IT2ZW5CT6
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=uploads.wavemaker.com
    command: npx cypress run --spec cypress/e2e/AppruntimeTests.cy.js,cypress/e2e/BasicTestsCookie.cy.js
    ipc: host
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
  cypress-runner-2:
    image: my-cypress-project
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
      - ./cypress/reports:/app/cypress/reports
    environment:
      - AWS_ACCESS_KEY_ID=AKIAYPLNK36IT2ZW5CT6
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=uploads.wavemaker.com
    command: npx cypress run --spec cypress/e2e/BasicTests.cy.js,cypress/e2e/FlakyTestsInSelinium.cy.js
    ipc: host
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
  cypress-runner-3:
    image: my-cypress-project
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
      - ./cypress/reports:/app/cypress/reports
    environment:
      - AWS_ACCESS_KEY_ID=AKIAYPLNK36IT2ZW5CT6
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=uploads.wavemaker.com
    command: npx cypress run --spec cypress/e2e/IframeTest.cy.js,cypress/e2e/WavemakerSpeedTest.cy.js
    ipc: host
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
