apiVersion: batch/v1
kind: Job
metadata:
  name: ${KUBE_JOB_NAME}
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
        - name: cypress
          image: ${IMAGE_NAME}
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -x ;
              echo "📁 BEFORE Cypress run: contents of /e2e" ;
              ls -R /e2e ;

              echo "🚀 Running Cypress..." ;
              npx cypress run --spec "${SPEC_FILES}" --env allureResultsPath=/e2e/${ALLURE_DIR} ;
              EXIT_CODE=$? ;

              echo "🧪 Cypress Exit Code: $EXIT_CODE" ;

              echo "📁 AFTER Cypress run: contents of /e2e" ;
              ls -R /e2e ;

              echo "📁 Checking Allure results directory: /e2e/${ALLURE_DIR}" ;
              ls -la /e2e/${ALLURE_DIR} || echo "❌ Allure directory not found" ;

              echo "☁️ Uploading to S3..." ;
              aws s3 cp "/e2e/${ALLURE_DIR}" "s3://wm-qa-automation/${JOB_NAME}/${BUILD_NUMBER}/" --recursive --acl public-read ;

              echo "✅ Uploaded to s3://wm-qa-automation/${JOB_NAME}/${BUILD_NUMBER}/" ;
              exit $EXIT_CODE
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            - name: BUILD_NUMBER
              value: "${BUILD_NUMBER}"
          volumeMounts:
            - name: project-volume
              mountPath: /e2e
      restartPolicy: Never
      volumes:
        - name: project-volume
          emptyDir: {}
  backoffLimit: 0
