apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
        - name: cypress
          image: ${IMAGE_NAME}
          command: ["/bin/sh", "-c"]
          args:
            - >
              npx cypress run --spec "${SPEC_FILES}" --env allureResultsPath=${ALLURE_DIR}
          env:
            - name: ALLURE_RESULTS_DIR
              value: "${ALLURE_DIR}"
          volumeMounts:
            - name: project-volume
              mountPath: /e2e
      restartPolicy: Never
      volumes:
        - name: project-volume
          emptyDir: {}
  backoffLimit: 0
