apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
        - name: cypress
          image: ${IMAGE_NAME}
          command: ["/bin/sh", "-c"]
          args:
            - >
              npx cypress run --spec "${SPEC_FILES}" --env allureResultsPath=${ALLURE_DIR} &&
              aws s3 cp "/e2e/${ALLURE_DIR}" "s3://wm-qa-automation/${JOB_NAME}/${BUILD_NUMBER}" --recursive --acl public-read
          env:
            - name: ALLURE_RESULTS_DIR
              value: "/e2e/${ALLURE_DIR}"
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            - name: BUILD_NUMBER
              value: "${BUILD_NUMBER}"
          volumeMounts:
            - name: project-volume
              mountPath: /e2e
      restartPolicy: Never
      volumes:
        - name: project-volume
          emptyDir: {}
  backoffLimit: 0
