apiVersion: batch/v1
kind: Job
metadata:
  name: ${KUBE_JOB_NAME}
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
        - name: cypress
          image: ${IMAGE_NAME}
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -x ;
              npx cypress run --spec "${SPEC_FILES}" --env allureResultsPath=${ALLURE_DIR} ;
              EXIT_CODE=$? ;
              echo "Cypress Exit Code: $EXIT_CODE" ;
              echo "Uploading Allure results..." ;
              ls -R ${ALLURE_DIR} ;
              aws s3 cp "${ALLURE_DIR}" "s3://wm-qa-automation/${JOB_NAME}/${BUILD_NUMBER}/" --recursive --acl public-read ;
              echo "✅ Uploaded to s3://wm-qa-automation/${JOB_NAME}/${BUILD_NUMBER}/" ;
              exit $EXIT_CODE
          env:
            - name: ALLURE_RESULTS_DIR
              value: "/e2e/${ALLURE_DIR}"
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            - name: BUILD_NUMBER
              value: "${BUILD_NUMBER}"
      restartPolicy: Never
  backoffLimit: 0
